name: CI Automation for SauceDemo & JSONPlaceholder

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Install dependencies
        run: mvn install -DskipTests=true

      - name: Run UI tests
        run: mvn test -Dtest=SauceDemoUITests

      - name: Run API tests
        run: mvn test -Dtest=JsonPlaceholderApiTests

      - name: Archive screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-screenshots
          path: target/screenshots/
