name: CI Automation for Juice Shop Tests
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome
        ports: [ 4444:4444 ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      - run: mvn install -DskipTests=true
      - run: mvn test -Dtest=JuiceShopUITests
      - run: mvn test -Dtest=JuiceShopApiTests
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ui-screenshots
          path: target/screenshots/
      - run: mvn jacoco:report
        if: always()
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jacoco-report
          path: target/site/jacoco/
